add check for null or empty

diff --git a/.github/workflows/update-sdk-version.yml b/.github/workflows/update-sdk-version.yml
--- a/.github/workflows/update-sdk-version.yml
+++ b/.github/workflows/update-sdk-version.yml
@@ -29,7 +29,12 @@ jobs:
       - name: Replace SDK Version
         run: |
           file_path="app-public/build.gradle.kts"
-          version_input="${{ github.event.inputs.new_version }}"
+          version_input="${{ github.event.inputs.new_version }}" 
+          if [ -z "$version_input" ]; then
+              echo "Error: new_version input is empty or not set."
+              exit 1
+          fi
+
           sed -i "s/val brivo_sdk_version = \".*\"/val brivo_sdk_version = \"${version_input}\"/" "$file_path"
 
       - name: Grant execute permission to Gradle wrapper
